/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORTV_H_RPCGEN
#define _SORTV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a[2000];
};
typedef struct numbers numbers;

struct funcreturn {
	int a;
	int b;
};
typedef struct funcreturn funcreturn;

#define SORTV_PROG 0x23451111
#define SORTV_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sort 1
extern  funcreturn * sort_1(numbers *, CLIENT *);
extern  funcreturn * sort_1_svc(numbers *, struct svc_req *);
extern int sortv_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sort 1
extern  funcreturn * sort_1();
extern  funcreturn * sort_1_svc();
extern int sortv_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);
extern  bool_t xdr_funcreturn (XDR *, funcreturn*);

#else /* K&R C */
extern bool_t xdr_numbers ();
extern bool_t xdr_funcreturn ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORTV_H_RPCGEN */
