/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sortv.h"
#define MAXN 2000
static struct funcreturn result;
int contador = 0;

funcreturn *
sort_1_svc(numbers *argp, struct svc_req *rqstp)
{

	if (!contador)
	{
		result.a = 0;
		result.b = 500000;
	}

	// compare the numbers to find the min and max
	for (int i = 0; i < MAXN; i++)
	{
		if (argp->a[i] > result.a)
			result.a = argp->a[i];
		if (argp->a[i] < result.b)
			result.b = argp->a[i];
	}

	contador++;
	if (contador == 250)
	{
		contador = 0;
	}

	return &result;
}
